// Copy only engine/craft blocks, never a film's story, cue list, score or pictures.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {args} from './lib/browser.mjs';
const a=args(process.argv.slice(2));
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const kind=a.kind, out=a.out&&path.resolve(a.out);
// A music film takes its duration from the analysed track: run analyze.mjs first.
const featPath=out&&path.join(path.dirname(out),'features.json');
if(kind==='music'&&out&&!fs.existsSync(featPath)){console.error(`no ${featPath}; run: node analyze.mjs <track> --film ${path.dirname(a.out)}`);process.exit(1);}
const duration=kind==='still'?1:kind==='music'?(out?JSON.parse(fs.readFileSync(featPath,'utf8')).duration:NaN):Number(a.duration);
if (!['film','still','music'].includes(kind) || !out || !Number.isFinite(duration) || duration<=0) {
  console.error('usage: node new-riso.mjs --kind film --duration 60 --out ../films/name/index.html\n       node new-riso.mjs --kind music --out ../films/name/index.html   (after analyze.mjs)\n       node new-riso.mjs --kind still --out ../prints/name/index.html');
  process.exit(1);
}
if(fs.existsSync(out)) throw Error(`Refusing to overwrite ${out}; edit its authoritative HTML`);
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const music=kind==='music';
const musicKit=music?read('tools/lib/music-kit.js'):'';
function between(s,start,end) {
  const lo=s.indexOf(start),hi=s.indexOf(end,lo+start.length);
  if(lo<0||hi<0) throw Error(`Source block changed: ${start} / ${end}. Check the donor before regenerating.`);
  return s.slice(lo,hi).trim();
}
const core=between(read('prints/workings/index.html'),'const PAPER =','/* ── prints');
const studies=read('studies/index.html');
const pattern=between(studies,'function dotPattern(', '/** Screen a greyscale');
const live=between(studies,'const scratch =','/* ── paper');
const motion=between(studies,'/* ── motion kit','/* ── studies');
const space=read('tools/lib/visual-kit.mjs').replace(/^export /gm,'');
const title=String(a.title||path.basename(path.dirname(out))).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const html=`<!doctype html>
<html lang="en"><meta charset="utf-8"><title>${title}</title>
<style>
html,body{margin:0;background:#242433;color:#ede8df;font:14px system-ui}
canvas{display:block;width:720px;height:720px}nav{max-width:696px;padding:12px;display:flex;gap:12px;align-items:center}
input{flex:1}button,a{color:inherit}a{display:none}[hidden]{display:none}button{background:#414153;border:0;padding:8px;cursor:pointer}
</style><canvas id="c"></canvas>${music?'<audio id="track" src="track.wav" preload="auto"></audio><script src="features.js"></script>':''}
<nav><button id="play">Play</button><button id="replay">Replay</button><input id="scrub" type="range" min="0" max="${duration}" value="0" step="0.0333333333"><output id="time">0</output><button id="record">Record</button><a id="download">Download</a></nav>
<script>
'use strict';
// Engine/craft snapshot generated by tools/new-riso.mjs. Edit this HTML for this work.
// Donors: prints/workings (baked print), studies/index (live tone/motion), tools/lib/visual-kit.
// Re-run the generator only to create a NEW file. This source owns all subsequent art edits.
const CSS=720, W=1080, OUT=1080, K=1, PITCH=4.6, DUR=${duration};
${core}
${pattern}
${live}
const wobbler=(key,n=3)=>makeWob(rngFor(key),n);
const easeOutCubic=u=>1-(1-u)**3, easeInQuad=u=>u*u;
const easeInOutCubic=u=>u<.5?4*u*u*u:1-(-2*u+2)**3/2;
${motion}
const Space=(()=>{
${space}
return {camera,plane,pathByLength,travel,hermite,ballistic};
})();
${musicKit}
// ART BEGIN: design a frame before adding a timeline. Blank paper is a scaffold, not finished art.
function drawArt(t) { }
const SHOTS=[]; // Optional review data: {id,start,end,readAt,action,transition}.
// ART END

const canvas=document.getElementById('c'),ctx=canvas.getContext('2d');
canvas.width=canvas.height=OUT;
paper=bakePaper();
const scrub=document.getElementById('scrub'),clockLabel=document.getElementById('time');
function render(t) {
  t=clamp(t,0,DUR); ctx.setTransform(1,0,0,1,0,0);ctx.globalAlpha=1;ctx.globalCompositeOperation='source-over';
  ctx.drawImage(paper,0,0);drawArt(t);scrub.value=t;clockLabel.value=t.toFixed(2);
}
function paintBaked(id) {
  ctx.save();ctx.globalCompositeOperation='multiply';ctx.drawImage(bakeScene(id,OUT),0,0);ctx.restore();
}
/* A frame slower than the frame interval cannot play live (live-plate films take
   100-200 ms): Play then renders every frame once into a WebP cache, shown as
   "Buffering n%", and plays from it at FPS; replays are immediate. Fast films play
   live. seek() and window.__riso stay live and pure; tools never touch the cache. */
const FPS=30,NF=Math.round(DUR*FPS),cache=[],bitmaps=new Map(),playBtn=document.getElementById('play');
const audio=document.getElementById('track');
let at=0,playing=false,epoch=0,recorder=null,recordURL=null,slow=null,buffering=false,filled=0;
function label(){playBtn.textContent=playing?'Pause':buffering?'Buffering '+Math.round(filled/(NF+1)*100)+'%':'Play';}
function start(){if(at>=DUR)at=0;epoch=performance.now()-at*1000;playing=true;label();if(audio){audio.currentTime=at;audio.play().catch(()=>{});}}
function pause(){if(playing)at=clamp(audio&&!audio.paused?audio.currentTime:(performance.now()-epoch)/1000,0,DUR);if(audio)audio.pause();playing=false;buffering=false;label();if(recorder?.state==='recording')recorder.stop();}
async function buffer(){
  buffering=true;label();const resume=at;
  for(let i=0;i<=NF&&buffering;i++){
    if(cache[i])continue;
    render(i/FPS);canvas.toBlob(b=>{cache[i]=b;filled++;},'image/webp',0.8);   // snapshots now, encodes alongside the next draw
    label();await new Promise(r=>setTimeout(r,0));
  }
  while(buffering&&filled<NF+1)await new Promise(r=>setTimeout(r,50));
  if(buffering){buffering=false;at=resume;start();}
}
function play(){
  if(at>=DUR)at=0;
  if(slow===null){const t0=performance.now();render(at);render(at);slow=(performance.now()-t0)/2>900/FPS;}
  if(!slow||filled>=NF+1)start();else buffer();
}
function seek(t){pause();at=clamp(t,0,DUR);render(at);}
playBtn.onclick=()=>playing||buffering?pause():play();
document.getElementById('replay').onclick=()=>{seek(0);play();};
scrub.oninput=()=>seek(Number(scrub.value));
addEventListener('keydown',e=>{if(e.target.matches('input'))return;if(['Space','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Space')playing||buffering?pause():play();if(e.code==='ArrowLeft')seek(at-1/FPS);if(e.code==='ArrowRight')seek(at+1/FPS);});
document.getElementById('record').onclick=()=>{
  if(recorder?.state==='recording'){pause();return;}
  const mime=['video/webm;codecs=vp8','video/webm;codecs=vp9','video/webm'].find(m=>MediaRecorder.isTypeSupported(m));
  if(!mime)throw Error('No supported recording codec; use tools/render.mjs');
  seek(0);const stream=canvas.captureStream(FPS),chunks=[];recorder=new MediaRecorder(stream,{mimeType:mime});
  recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};
  recorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());if(recordURL)URL.revokeObjectURL(recordURL);recordURL=URL.createObjectURL(new Blob(chunks,{type:mime}));const a=document.getElementById('download');a.href=recordURL;a.download='preview.webm';a.style.display='inline';};
  recorder.start();play();
};
function tick(now){
  if(playing){
    at=clamp(audio&&!audio.paused?audio.currentTime:(now-epoch)/1000,0,DUR);   // the track is the clock when it plays
    if(!slow)render(at);
    else{
      const i=Math.min(NF,Math.floor(at*FPS));
      for(let j=i;j<Math.min(NF+1,i+8);j++)if(cache[j]&&!bitmaps.has(j)){bitmaps.set(j,null);createImageBitmap(cache[j]).then(b=>bitmaps.set(j,b));}
      for(const [j,b] of bitmaps)if(j<i-1){if(b)b.close();bitmaps.delete(j);}
      const b=bitmaps.get(i);
      if(b){ctx.setTransform(1,0,0,1,0,0);ctx.globalAlpha=1;ctx.globalCompositeOperation='source-over';ctx.drawImage(b,0,0);scrub.value=at;clockLabel.value=at.toFixed(2);}
    }
    if(at>=DUR)pause();
  }
  requestAnimationFrame(tick);
}
window.__riso={duration:DUR,ready:false,seek,shots:SHOTS${music?",audioFile:'track.wav'":''}};
for(const id of Object.keys(SCENES))bakeScene(id,OUT);
seek(Number(new URLSearchParams(location.search).get('t'))||0);
${kind==='still'?"document.querySelector('nav').hidden=true;":"requestAnimationFrame(tick);"}
window.__riso.ready=true;
</script></html>
`;
fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,html,{flag:'wx'});
console.log(`Created blank ${kind} source: ${out}\nAdd art in ART BEGIN. No inherited scenes, cues, score or ending.`);
